### ISSUE TITLE
Formalize generic type names for cross-platform consistency

### ISSUE THREAD

**Issue by pingpongboss** [material-motion/material-motion-starmap#102]
On Android, prefer `Property<T, V>`, `Observer<T>`.

In general, `T` for "target type" and `V` for "value type".
In most cases where there is a single generic type, `T` is often used for "type".

**Comment by jverkoey** [comment]
In context of discussing value types, it's common to need to map from one value type to another.

`T => U` is easier to read than
`V => U`

So `V` might be an ambiguous symbol to use for value types.

`O` is presently being used for Observer in the Observable spec.

`O` could be a reasonable candidate for object type in general.

**Comment by jverkoey** [comment]
The things we need to type:

- Objects
- Values
- Mapped values (`U`)

**Comment by pingpongboss** [comment]
Also important to keep in mind that the generic type names are only valid *within* the context of the class they're declared in.

Which is to say that I'm OK with the following:

`Property<T, V>` for `object type` and `value type`
`MotionObservable<T>` for `value type`.

Even though `value type` is defined using a different name in the two classes.

This is similar to
```
Observable<Foo> fooStream;
Observable<Bar> barStream = map(fooStream, FOO_TO_BAR_TRANSFORM); // [1].
Observable<Qux> quxStream = map(barStream, BAR_TO_QUX_TRANSFORM); // [2].
```

In this case, `barStream` is `map()`'s `<U>` in `[1]`, but the same `barStream` is `map()`'s `<T>` in `[2]`.

However, I can accept that someone else may make the opposing argument.

**Comment by jverkoey** [comment]
Ah, interesting. Good point about the external users not caring what the internal names are.

My primary concern with reusing T to mean different things in different places is for us when we're moving between class implementations. In this sense I'd prefer if we could be consistent so T always means the same kind of generic type.

**Comment by jverkoey** [comment]
I'd like to propose the following convention:

- Objects `O`
- Values `T`
- Mapped values `U`

`map<T, U>` maps a value of type T to U.
`Observable<O>` has an object of type O.
`Observer<T>` references a value of type T.

**Comment by pingpongboss** [comment]
Your proposal is missing a name and example for "target object". I assume you want "target object" to be `O` as well as observer?

My main problem is that this implies `Property<O, T>` which I hate hate hate since it's usually `Property<T, V>` on android.

**Comment by jverkoey** [comment]
This may not be as much of a concern because you're making use of the system Property type. Is that a fair assessment?

**Comment by pingpongboss** [comment]
Mm maybe! But I may introduce `Getter` and `Setter`. Maybe I would want to use `Getter<V>` and `Setter<V>` to be consistent with the platform's `Property<T, V>`?

**Comment by jverkoey** [comment]
Can you explore your concern here in code so we can get a feeling for it?

**Comment by pingpongboss** [comment]
```
Property<Target, Value> property;
Target target;

stream.writeTo(property, target); // [1].


MotionObservable<V> {
  /**
   * [1].
   */
  public void <T> writeTo(Property<T, V> property, T target) { }
}
```

This one is tricky. There are several opposing forces:

1. You would rather define `MotionObservable<T>` because "V and U are similar".
1. You would rather define `O target` because "O is for object".
1. I would like to define `Property<T, V>` because it matches the system, thus `T target` because it matches the property, and also thus `MotionObservable<V>`.

**Comment by jverkoey** [comment]
The alternative implementation, for comparison:

```
Property<Target, Value> property;
Target target;

stream.writeTo(property, target); // [1].

MotionObservable<T> {
  /**
   * [1].
   */
  public void <O> writeTo(Property<O, T> property, O target) { }
}
```

**Comment by jverkoey** [comment]
I think the latter feels ok; we haven't pushed the O concept up to the client and we're consistent within our Observable ecosystem. E.g. another operator might look like this:

```

MotionObservable<T> {
  /**
   * [1].
   */
  public void filter(filter: T -> Bool) { }
}
```

**Comment by pingpongboss** [comment]
Which isn't too bad for me. Let me summarize my pov:

I like:
 - `MotionObservable<T>` works well. Though imo `MotionObservable<V> works just as well.`
 - `filter(filter: T -> Bool)` works well too. Same for `filter(filter: V -> Bool)` though

I dislike:
 - `Property<O, T>` because it conflicts with the system.
 - `O target` when `<T>` also exists nearby, because my brain wants to associate `<T>` with target.

**Comment by jverkoey** [comment]
Would something like `ObjectType` help disambiguate as a compromise?

**Comment by pingpongboss** [comment]
I think i would prefer `<O>` to `<ObjectType>` which is wordy and more non-standard

**Comment by jverkoey** [comment]
We're going with the following standard:

- Objects `O`
- Values `T`
- Mapped values `U`
