### ISSUE TITLE
Consider alternative names for sources

### ISSUE THREAD

**Issue by jverkoey** [material-motion/material-motion-starmap#108]
Context: https://github.com/material-motion/streams-android/issues/12

My inclination is no, insofar that a source will be documented and discussed as a special type of observable. @pingpongboss is concerned that the type might be unexpected.

Some options:

1. Keep source. Heavily educate that it is an Observable.
2. Make Source a distinct type.
3. Rename Source to SourceObservable.

**Comment by pingpongboss** [comment]
A big problem with #1 is that for Java, operators that want to return a MotionObservable<Gesture> will have to return a GestureSource instead. Now, you have a source that's NOT a source, but a product of some operation!

**Comment by jverkoey** [comment]
Oh my! That is gross. I suppose the fourth option I missed, which is the one we currently enploy, is to not have a source type at all.

Is it possible to have a java file export a function like gestureSource in any way?

**Comment by pingpongboss** [comment]
No :( you have to define the static function somewhere.

The way I have it right now with `GestureSource.from(gesture)` is similar to the 4th option. It's only a class for the sake of holding a function.

**Comment by jverkoey** [comment]
That's :( for sure

Well! So it is. Let's keep the `*Source.from` pattern then :)
