### ISSUE TITLE
Scheduler.activityState

### ISSUE THREAD

**Issue by appsforartists** [material-motion/material-motion-starmap#28]
Right now, the [Scheduler spec](https://material-motion.gitbooks.io/material-motion-starmap/content/specifications/runtime/scheduler.html) prescribes an `activityState` property with two states (`active` and `idle`).

Why isn't this just a Boolean (e.g. `scheduler.isActive`)?

**Comment by jverkoey** [comment]
There had previously been a concept of a "Starting" state that has since been removed. It's likely reasonable to turn this in to a bool.
