### ISSUE TITLE
Springs and timelines

### ISSUE THREAD

**Issue by appsforartists** [material-motion/material-motion-starmap#32]
I'm curious how the timeline works when progress is driven in a non-linear way (e.g. by a gesture or a spring).  Seems like there's risk for the whole thing to feel on-rails/canned.

**Comment by jverkoey** [comment]
This will be something we document in time at L2 levels of documentation. The short version is that some types of animations will want to be "on rails" while others will benefit from being purely spring-driven. Our job will be to find effective ways to educate when to use one or the other.
