### ISSUE TITLE
Consider renaming DelegatedPerforming to ContinuousPerforming

### ISSUE THREAD

**Issue by jverkoey** [material-motion/material-motion-starmap#42]
ActivityPerforming more accurately reflects what conforming to this protocol means: the performer is expected to indicate to the runtime when some form of work is active, be it an active gesture recognizer or an active animation.

**Comment by jverkoey** [comment]
The spec has been updated.

https://material-motion.gitbooks.io/material-motion-starmap/content/specifications/runtime/performer.html

**Comment by appsforartists** [comment]
You use both `token vendor` and `token generator` in the pseudo-code.  Is one preferred?

**Comment by jverkoey** [comment]
token generator
