### ISSUE TITLE
Spec out "Springs" motion family

### ISSUE THREAD

**Issue by jverkoey** [material-motion/material-motion-starmap#50]
Spec: https://material-motion.gitbooks.io/material-motion-starmap/content/specifications/motion_family/springs.html

**Comment by appsforartists** [comment]
Physics is too broad a term for what this is.  Can we call it a spring family?

**Comment by jverkoey** [comment]
Deal.

**Comment by jverkoey** [comment]
This motion family is now called "Momentum conservation" and we've begun our initial discussion on the terminology.

**Comment by jverkoey** [comment]
SpringTo and ConfigureSpring now spec'd out.
