### ISSUE TITLE
Should we make SpringConfiguration a required property on SpringTo?

### ISSUE THREAD

**Issue by jverkoey** [material-motion/material-motion-starmap#67]
SpringTo's current spec requires a its configuration to persist in the performer until another configuration is provided. The argument for this behavior is **convenience** in the case of needing to change the destination multiple times without affecting the spring's configuration.

This behavior is _magic_. It requires an underlying understanding of the performer's behavior that can only be learned from documentation. I'd like to argue that this leads to somewhat confusing and difficult-to-debug code.

Consider the following trimmed-down implementation of an interaction:

```
func gestureDidChange(_ gestureRecognizer: UIGestureRecognizer) {
  let configuration = SpringConfiguration(tension: 1000, friction: sqrt(4 * 1000))

  let scaleSpring = SpringTo(.layerScaleXY, destination: CGPoint(x: scale, y: scale))
  scaleSpring.configuration = configuration
  scheduler.addPlan(scaleSpring, to: view.layer)
}

func gestureDidEnd(_ gestureRecognizer: UIGestureRecognizer) {
  let scaleSpring = SpringTo(.layerScaleXY, destination: CGPoint(x: 1, y: 1))
  scheduler.addPlan(scaleSpring, to: view.layer)
}
```

At first glance what might you expect the behavior of the spring to be when the gesture ends? Without knowing that performers keep configuration in memory, you'd likely assume that the values would spring with the "stock" configuration values.

## Possible solutions

Consider the following code:

```
let positionSpring = SpringTo(.layerPosition, destination: bounds.midPoint + center * scaleFactor)
scheduler.addPlan(positionSpring, to: view.layer)
```

Should the expected behavior here be:

1. Use the "stock" SpringTo configuration values.
2. Use the existing SpringTo configuration values. [current implementation]
3. A compiler error because configuration must always be explicitly provided. [proposed solution]

I'm leaning towards 3 because it ensures that the Director code is as explicit about behavior as possible; no hidden defaults or behavior. If someone finds that creating a SpringTo plan every time is onerous then they can always cache the SpringTo instance and change the destination as needed.

**Comment by pingpongboss** [comment]
This one is tough. I dislike #3 because it makes the "normal use case" difficult. The normal use case being the set-and-forget example that you included

```
let positionSpring = SpringTo(.layerPosition, destination: bounds.midPoint + center * scaleFactor)
scheduler.addPlan(positionSpring, to: view.layer)
```

I think there should always be a sane default, so either 1 or 2.

**Comment by jverkoey** [comment]
Spoke with Mark offline. Aim is to move to 1.
- [ ] Configuration is non-null and initialized with reasonable defaults.
- [ ] Configuration always overwrites current SpringTo configuration.
