### ISSUE TITLE
Writing plan information out to the console

### ISSUE THREAD

**Issue by jverkoey** [material-motion/material-motion-starmap#73]
I've written up a spec on how plans might be written out to the console. View the spec here:

https://material-motion.github.io/material-motion/starmap/specifications/runtime/Runtime/tracing/ConsoleLoggingTracer

And an implementation of the proposed changes here: http://codereview.cc/D1897

**Comment by jverkoey** [comment]
LGTM via @pingpongboss in Discord.

**Comment by appsforartists** [comment]
We're accepting specs via Discord now?  This is marked "stable," and I hadn't even seen it.

**Comment by jverkoey** [comment]
This one's pretty light-weight. Can re-open any thread with additional thoughts.

**Comment by appsforartists** [comment]
It's easy enough to bikeshed over the syntax (e.g. why `let`), but probably not substantive enough to be worthwhile.

Not sure what `@` means as a type though.

**Comment by jverkoey** [comment]
Removed the lets.

**Comment by jverkoey** [comment]
http://codereview.cc/D1930

**Comment by appsforartists** [comment]
Thanks.  What's `@` as a type mean?

**Comment by jverkoey** [comment]
In swift-land is just an "unknown" type.
